import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
import fs from 'node:fs'
const require = createRequire(process.env.CODEX_NODE_MODULES + '/package.json')
const { chromium } = require('playwright')
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const base = process.env.ACCOUNT_TEST_BASE || 'http://127.0.0.1:5199'
const out = new URL('../recovery-evidence/account-workspace/', import.meta.url)
fs.mkdirSync(out, { recursive: true })
const errors = []
async function page() {
  const context = await browser.newContext({ viewport: { width: 1365, height: 1000 } })
  const p = await context.newPage()
  p.on('pageerror', e => errors.push(e.message))
  return p
}
async function signIn(p, name, password, dashboard = false) {
  await p.goto(base + '/EpicVM/settings')
  await p.getByLabel('Account type').selectOption(dashboard ? 'dashboard' : 'portal')
  await p.getByLabel('Username', { exact: true }).fill(name)
  await p.getByLabel('Password', { exact: true }).fill(password)
  await p.getByRole('button', { name: 'Sign in', exact: true }).click()
  await p.getByRole('heading', { name: 'Settings', exact: true }).waitFor()
}
try {
  const user = await page()
  await signIn(user, 'alice', 'portal-original')
  await user.getByLabel('Subject', { exact: true }).fill('Browser test VM request')
  await user.getByLabel('What do you need?').fill('Windows gaming machine for this isolated browser test.')
  await user.getByRole('button', { name: 'Send request or report' }).click()
  await user.getByRole('heading', { name: 'Browser test VM request', exact: true }).waitFor()
  await user.getByLabel(/^Type/).selectOption('bug')
  await user.getByLabel('Subject', { exact: true }).fill('Browser test bug report')
  await user.getByLabel('Details', { exact: true }).fill('This is a local fixture report, not a real incident.')
  await user.getByRole('button', { name: 'Send request or report' }).click()
  await user.getByRole('heading', { name: 'Browser test bug report' }).waitFor()
  await user.getByLabel('Current password', { exact: true }).fill('portal-original')
  await user.getByLabel('New password', { exact: true }).fill('portal-browser-new')
  await user.getByLabel('Confirm new password').fill('portal-browser-new')
  await user.getByRole('button', { name: 'Update password', exact: true }).click()
  await user.getByRole('status').filter({ hasText: 'Password updated.' }).waitFor()
  await user.screenshot({ path: new URL('settings-desktop.png', out).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true })
  await user.setViewportSize({ width: 390, height: 844 })
  assert.equal(await user.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
  await user.screenshot({ path: new URL('settings-mobile.png', out).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true })
  const admin = await page()
  await signIn(admin, 'manager', 'portal-original')
  await admin.getByRole('link', { name: 'Management', exact: true }).click()
  await admin.getByRole('heading', { name: 'Management', exact: true }).waitFor()
  await admin.getByRole('heading', { name: 'Create a new VM', exact: true }).waitFor()
  await admin.getByText('Fixture Hyper-V host').first().waitFor()
  await admin.getByRole('heading', { name: 'Managed machines', exact: true }).waitFor()
  const machine = admin.locator('article').filter({ has: admin.getByRole('heading', { name: 'Fixture gaming PC', exact: true }) })
  await machine.getByRole('button', { name: 'Stop', exact: true }).waitFor()
  await machine.getByRole('button', { name: 'Restart', exact: true }).waitFor()
  await machine.getByRole('link', { name: 'Open console', exact: true }).waitFor()
  await admin.getByText(/Recent creation history/).waitFor()
  await admin.getByRole('link', { name: /Advanced dashboard/ }).waitFor()
  await admin.screenshot({ path: new URL('management-machines-desktop.png', out).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true })
  assert.equal(await admin.getByLabel(/^Host/).inputValue(), 'local')
  assert.equal(await admin.getByRole('button', { name: 'Create normal VM', exact: true }).isEnabled(), true)
  await admin.getByText('This creates the same normal server VM offered by the full dashboard and starts it immediately.').waitFor()
  await admin.getByLabel(/^Host/).selectOption('epic-pc')
  assert.equal(await admin.getByRole('button', { name: 'Create VM', exact: true }).isEnabled(), true)
  await admin.getByLabel(/^Profile/).selectOption('omarchy')
  await admin.getByText('This host is not ready for the selected profile.').waitFor()
  assert.equal(await admin.getByRole('button', { name: 'Create VM', exact: true }).isDisabled(), true)
  await admin.getByLabel(/^Profile/).selectOption('gaming')
  await admin.getByRole('button', { name: /Requests\s/ }).click()
  const request = admin.locator('article').filter({ has: admin.getByRole('heading', { name: 'Browser test VM request' }) })
  await request.getByLabel('Next step').selectOption('fulfilled')
  await request.locator('select[name=resourceKey]').selectOption('vm:epic-pc:fixture-one')
  await request.getByLabel('Reply', { exact: true }).fill('Your fixture VM has been assigned.')
  await request.getByRole('button', { name: 'Send update' }).click()
  await admin.getByText('Request updated. The response is visible in account settings.').waitFor()
  await admin.getByRole('button', { name: /Accounts\s/ }).click()
  const pending = admin.locator('article').filter({ has: admin.getByRole('heading', { name: 'pendingmember', exact: true }) })
  await pending.getByRole('button', { name: 'Approve account' }).click()
  await pending.getByText('approved', { exact: true }).waitFor()
  const alice = admin.locator('article').filter({ has: admin.getByRole('heading', { name: 'alice', exact: true }) })
  await alice.getByText('VM assignments · 1', { exact: true }).click()
  assert.equal(await alice.locator('input[type=checkbox]').isChecked(), true)
  await alice.getByText('Reset password', { exact: true }).first().click()
  await alice.getByLabel('New password', { exact: true }).fill('admin-reset-fixture')
  await alice.getByRole('button', { name: 'Reset password', exact: true }).click()
  await admin.getByRole('status').filter({ hasText: 'Account updated.' }).waitFor()
  await admin.screenshot({ path: new URL('management-desktop.png', out).pathname.replace(/^\/(\w:)/, '$1'), fullPage: true })
  await admin.getByRole('button', { name: /Feedback\s/ }).click()
  const bug = admin.locator('article').filter({ has: admin.getByRole('heading', { name: 'Browser test bug report' }) })
  await bug.getByLabel('Next step').selectOption('resolved')
  await bug.getByLabel('Reply', { exact: true }).fill('The fixture issue has been resolved.')
  await bug.getByRole('button', { name: 'Send update' }).click()
  await bug.waitFor({ state: 'detached' })
  await user.reload()
  await signIn(user, 'alice', 'admin-reset-fixture')
  await user.getByText('The fixture issue has been resolved.').waitFor()
  await user.getByText('Your fixture VM has been assigned.').waitFor()
  await user.goto(base + '/EpicVM/Management')
  await user.getByRole('heading', { name: 'Administrator access required' }).waitFor()
  const config = await page()
  await signIn(config, 'rootadmin', 'admin-original', true)
  await config.getByLabel('Current password', { exact: true }).fill('admin-original')
  await config.getByLabel('New password', { exact: true }).fill('admin-browser-new')
  await config.getByLabel('Confirm new password').fill('admin-browser-new')
  await config.getByRole('button', { name: 'Update password', exact: true }).click()
  await config.getByRole('status').filter({ hasText: 'Password updated.' }).waitFor()
  await config.getByRole('button', { name: 'Sign out', exact: true }).click()
  await signIn(config, 'rootadmin', 'admin-browser-new', true)
  assert.deepEqual(errors, [])
  console.log('PASS: browser user/admin requests, machine fleet, provisioning history, reply, assignment, approval, password changes/reset, role guard, mobile overflow, no JS exceptions.')
} finally { await browser.close() }
