import { createRequire } from 'node:module'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { spawnSync } from 'node:child_process'
const require = createRequire('C:/Users/Epic/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json')
const { chromium } = require('playwright')
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true })
const context = await browser.newContext()
const page = await context.newPage()
const errors = []
page.on('pageerror', e => errors.push(e.message))
const base = 'http://127.0.0.1:5201'
const out = new URL('../recovery-evidence/shared-games-ui/', import.meta.url)
fs.mkdirSync(out, { recursive: true })
try {
  await page.goto(base + '/EpicVM/Management')
  await page.getByLabel('Account type').selectOption('portal')
  await page.getByLabel('Username', {exact:true}).fill('manager')
  await page.getByLabel('Password', {exact:true}).fill('portal-original')
  await page.getByRole('button', {name:'Sign in',exact:true}).click()
  const panel = page.locator('section').filter({has:page.getByRole('heading',{name:'Shared games',exact:true})})
  await panel.getByText('FNF Dustin',{exact:true}).first().waitFor()
  // Bounded semantic verification uses the installed Jev policy; deterministic
  // assertions still establish each state transition and final assignment.
  const state = {url:page.url(),title:await page.title(),text:await panel.innerText(),actions:[
    {id:'add',kind:'click',node:'add',role:'button',label:'Add Game'},
    {id:'wait',kind:'wait',label:'Wait for loading'}]}
  const jev = spawnSync('uv',['run','--project','E:/Projects/Documents/CodexProj/tools/jev-ultrafast','python','scripts/shared_games_jev.py','--goal','Add a new shared game using an existing host installation.'],{input:JSON.stringify(state),encoding:'utf8',cwd:new URL('..',import.meta.url).pathname.replace(/^\/(\w:)/,'$1')})
  fs.writeFileSync(new URL('jev-result.json',out),jev.stdout || JSON.stringify({unavailable:true}))
  assert.equal(jev.status,0,jev.stderr)
  assert.equal(JSON.parse(jev.stdout).choice,'add')
  await panel.getByRole('button',{name:'Add Game',exact:true}).click()
  await panel.getByLabel('Game name',{exact:true}).fill('Fixture portable game')
  await panel.getByLabel('Game ID',{exact:true}).fill('fixture-portable')
  await panel.getByLabel('Installation folder on the host',{exact:true}).fill('D:\\FixtureGame')
  await panel.getByRole('button',{name:'Inspect and add game',exact:true}).click()
  await panel.getByText('Fixture portable game',{exact:true}).first().waitFor()
  await panel.getByRole('combobox',{name:/^Gaming machine/}).selectOption('Fixture gaming PC')
  await panel.getByLabel('FNF Dustin',{exact:true}).check()
  await panel.getByRole('button',{name:'Apply games to VM',exact:true}).click()
  await panel.getByRole('status').filter({hasText:'assign: complete'}).waitFor()
  await page.screenshot({path:new URL('management-desktop.png',out).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true})
  const userContext = await browser.newContext()
  const user = await userContext.newPage()
  await user.goto(base+'/EpicVM/settings')
  await user.getByLabel('Username',{exact:true}).fill('alice')
  await user.getByLabel('Password',{exact:true}).fill('portal-original')
  await user.getByRole('button',{name:'Sign in',exact:true}).click()
  await user.getByRole('heading',{name:'Settings',exact:true}).waitFor()
  const games = await user.request.get(base+'/EpicVM/api/account/games')
  assert.equal(games.status(),200,await games.text())
  assert.equal((await games.json()).machines[0].games[0].id,'fnf-dustin')
  await user.route('**/portal/api/vms', async route => { await new Promise(resolve => setTimeout(resolve, 1800)); await route.continue() })
  await user.goto(base+'/EpicVM/portal', {waitUntil:'domcontentloaded'})
  await user.getByText('Your account is connected',{exact:true}).waitFor()
  await user.getByText('Finding your machines and checking their latest status…',{exact:true}).waitFor()
  await user.getByRole('heading',{name:'Fixture gaming PC',exact:true}).waitFor()
  const userGames = user.locator('details.evm-shared-games')
  await userGames.getByText('Your games and desktops',{exact:true}).waitFor()
  assert.equal(await userGames.getAttribute('open'),null)
  await userGames.locator('summary').click()
  await user.getByRole('listitem').filter({hasText:'FNF Dustin'}).waitFor()
  await user.waitForTimeout(8000)
  assert.equal(await userGames.getAttribute('open'),'')
  assert.equal(await user.getByText('Loading games…').count(),0)
  assert.equal(await user.getByText('Loading your machines…').count(),0)
  await user.screenshot({path:new URL('user-dashboard.png',out).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true})
  await panel.getByLabel('FNF Dustin',{exact:true}).uncheck()
  const removal = page.waitForResponse(response => response.url().endsWith('/management/games/jobs') && response.request().method() === 'POST')
  await panel.getByRole('button',{name:'Apply games to VM',exact:true}).click()
  assert.equal((await removal).ok(),true)
  await panel.getByRole('status').filter({hasText:'assign: complete'}).waitFor()
  assert.deepEqual((await (await user.request.get(base+'/EpicVM/api/account/games')).json()).machines[0].games,[])
  await page.setViewportSize({width:390,height:844})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true)
  await page.screenshot({path:new URL('management-mobile.png',out).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true})
  assert.deepEqual(errors,[])
  console.log('PASS: local-path add, catalog display, assignment, removal, user filtering, mobile width, no browser exceptions.')
} catch(error) { await page.screenshot({path:new URL('failure.png',out).pathname.replace(/^\/(\w:)/,'$1'),fullPage:true}); console.error((await page.locator('body').innerText()).slice(-6000)); throw error }
finally {await browser.close()}
