#Requires -RunAsAdministrator
<#
    Builds an immutable EpicVM Ubuntu Server template from a pinned Ubuntu ISO.

    Why Ubuntu rather than the existing Windows flow: a Windows template needs a
    host-side secret that must match a secret baked into the image, and that
    coupling re-breaks on every rebuild, rotation, or restore. Ubuntu guests get a
    per-VM SSH keypair at provision time instead, so there is nothing to drift.

    This builder is intentionally plan-only unless -Execute is supplied, mirroring
    scripts/Build-EpicVMOmarchyTemplate.ps1. It:

      1. verifies the pinned ISO sha256
      2. creates a disposable Gen2 builder VM on a NAT switch with egress
      3. installs Ubuntu unattended via cloud-init NoCloud (autoinstall + a cidata
         seed) - no OOBE, no unattend passes, no sysprep
      4. bakes sshd, the epicvm agent account with NOPASSWD sudo, and base tooling
      5. sanitizes (burn the seed, drop host keys, drop tailscale identity)
      6. exports and publishes an immutable VHDX plus a hash-pinned manifest

    No GPU partition and no Sunshine/streaming: the ubuntu profile is headless and
    SSH-first.
#>
[CmdletBinding()]
param(
    [switch]$Execute,
    [string]$IsoPath = 'E:\EpicVM\install-media\ubuntu-24.04.3-live-server-amd64.iso',
    [string]$ExpectedIsoSha256 = 'c3514bf0056180d09376462a7a1b4f213c1d6e8ea67fae5c25099c6fd3d8274b',
    [string]$TemplateName = 'ubuntu-24.04-lts',
    [string]$TemplateRoot = 'E:\EpicVM\templates',
    [string]$WorkingRoot = 'E:\EpicVM\template-work',
    [string]$BuilderVmName = 'EpicVM-Ubuntu-TemplateBuilder',
    [string]$BuilderSwitch = 'Default Switch',
    [string]$AgentUser = 'epicvm',
    [string]$TimeZone = 'America/New_York',
    [long]$DiskSizeBytes = 12884901888,
    [int]$CpuCount = 4,
    [long]$MemoryBytes = 8589934592,
    [string]$ReportPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Stage {
    param([string]$Message)
    # Routed to the host stream so stage logging never contaminates a function's
    # return value. A plain Write-Output here would prepend the log lines to the
    # caller's result and break strict-mode property access.
    Write-Host ("[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $Message)
}

function Get-EpicVMUbuntuPlan {
    return [ordered]@{
        templateName = $TemplateName
        isoPath = $IsoPath
        expectedIsoSha256 = $ExpectedIsoSha256
        templateRoot = $TemplateRoot
        workingRoot = $WorkingRoot
        builderVm = $BuilderVmName
        switch = $BuilderSwitch
        agentUser = $AgentUser
        diskSizeBytes = $DiskSizeBytes
        cpuCount = $CpuCount
        memoryBytes = $MemoryBytes
        guestOs = 'Ubuntu Server'
        managementTransport = 'tailscale_ssh'
        consoleBackend = 'none'
        gpu = $false
        bootMode = 'uefi'
        bootPolicy = 'gen2-uefi'
        secureBoot = $false
        vTpm = $false
        fullCopy = $true
        immutable = $true
        noGuestSecrets = $true
        bootstrap = 'per-vm-ssh-keypair'
    }
}

function Test-EpicVMUbuntuPreconditions {
    $plan = Get-EpicVMUbuntuPlan
    $checks = [ordered]@{
        isoPresent = Test-Path -LiteralPath $plan.isoPath -PathType Leaf
        switchPresent = $null -ne (Get-VMSwitch -Name $plan.switch -ErrorAction SilentlyContinue)
        builderVmPresent = $null -ne (Get-VM -Name $plan.builderVm -ErrorAction SilentlyContinue)
        workingRootWritable = $false
        isoHashMatches = $false
    }
    if ($checks.isoPresent) {
        $actual = (Get-FileHash -LiteralPath $plan.isoPath -Algorithm SHA256).Hash.ToLowerInvariant()
        $checks.isoHashMatches = $actual -eq $plan.expectedIsoSha256
        $checks.isoActualSha256 = $actual
    }
    try {
        $parent = Split-Path -Parent $plan.workingRoot
        $probe = Join-Path $parent ('.epicvm-write-probe-' + [guid]::NewGuid().ToString('N'))
        New-Item -ItemType Directory -Path $probe -Force | Out-Null
        Remove-Item $probe -Recurse -Force -ErrorAction SilentlyContinue
        $checks.workingRootWritable = $true
    } catch { $checks.workingRootWritable = $false }
    return $checks
}
function New-EpicVMUbuntuCloudInit {
    <#
        Returns the NoCloud seed files. The autoinstall payload runs on the ISO's
        first boot; the same seed is reused at provision time so a clone is
        reconfigured without a console.
    #>
    param(
        [Parameter(Mandatory)][string]$VmName,
        [Parameter(Mandatory)][string]$AgentUser,
        [Parameter(Mandatory)][string]$PasswordHash,
        [string]$AuthorizedKey = '',
        [string]$TimeZone = 'America/New_York',
        [long]$DiskSizeBytes = 12884901888
    )
    $userData = @'
#cloud-config
# EpicVM unattended Ubuntu install. Generated by Build-EpicVMUbuntuTemplate.ps1.
identity:
  hostname: $VmName
  username: $AgentUser
  password: "$passwordHash"
  # The agent account is locked for interactive console use; the SSH key is the
  # only intended login. PasswordAuthentication is disabled in sshd_config.
  lock_passwd: true
  sudo: ALL=(ALL) NOPASSWD:ALL
  ssh_authorized_keys:
    - $AuthorizedKey
storage:
  layout:
    name: direct
  overwrite: true
  config:
    # The seed is a 64MB cidata VHDX and must never be wiped. Matching
    # the largest disk is the reliable selector on this host because
    # Hyper-V does not expose a stable serial here (Get-VHD .DiskId is
    # empty), so a serial match is not available.
    - type: disk
      ptable: gpt
      match:
        size: largest
      wipe: install
updates: security
timezone: $TimeZone
keyboard:
  layout: us
packages:
  - ca-certificates
  - curl
  - git
  - jq
  - openssh-server
  - python3
  - python3-pip
  - python3-venv
  - build-essential
  - htop
  - unzip
late-commands:
  # NOPASSWD sudo is written explicitly so it survives any image default, and
  # sudo is verified before the install is allowed to report success.
  - curtin in-target -- mkdir -p /etc/sudoers.d
  - curtin in-target -- printf 'epicvm ALL=(ALL) NOPASSWD:ALL\\n' > /etc/sudoers.d/90-epicvm
  - curtin in-target -- chmod 0440 /etc/sudoers.d/90-epicvm
  - curtin in-target -- visudo -c -f /etc/sudoers.d/90-epicvm
  - curtin in-target -- systemctl enable --now ssh
  - curtin in-target -- install -d -m 755 /etc/ssh/sshd_config.d
  - curtin in-target -- printf 'PubkeyAuthentication yes\\nPasswordAuthentication no\\nPermitEmptyPasswords no\\nPermitRootLogin no\\n' > /etc/ssh/sshd_config.d/60-epicvm.conf
  - curtin in-target -- sshd -t
  - curtin in-target -- curl -fsSL https://pk.tailscale.com/stable/ubuntu/noble.gpg | tee /usr/share/keyrings/tailscale-archive-keyring.gpg > /dev/null
  - curtin in-target -- printf 'deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pk.tailscale.com/stable/ubuntu noble\\n' > /etc/apt/sources.list.d/tailscale.list
  - curtin in-target -- apt-get update
  - curtin in-target -- apt-get install -y tailscale
  - curtin in-target -- curl -fsSL https://deb.nodesource.com/setup_22.x -o /tmp/nodesource.sh
  - curtin in-target -- bash /tmp/nodesource.sh
  - curtin in-target -- apt-get install -y nodejs
  - curtin in-target -- rm -f /tmp/nodesource.sh
  - curtin in-target -- apt-get clean
shutdown: reboot
'@
$passwordHash = $null
    return [ordered]@{
        'meta-data'   = ("instance-id: $VmName`nlocal-hostname: $VmName`n")
        'user-data'   = $userData
        'network-config' = @'
version: 2
ethernets:
  primary:
    match:
      name: "e*"
    dhcp4: true
    dhcp-identifier: mac
optional: true
'@
    }
}
function New-EpicVMUbuntuSeedDisk {
    <#
        Builds a 64MB FAT32 cidata VHDX. Reuses the same shape the Omarchy
        provider already uses (New-EpicVMOmarchySeedDisk) so both Linux profiles
        share one seed mechanism.
    #>
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][System.Collections.IDictionary]$Files,
        [scriptblock]$CommandInvoker = $null
    )
    function Invoke-Cmd { param([string]$Name,[hashtable]$Parameters)
        if ($null -ne $CommandInvoker) { return & $CommandInvoker $Name $Parameters }
        $command = Get-Command -Name $Name -ErrorAction SilentlyContinue
        if ($null -eq $command) { throw ("epicvm_ubuntu_provider_unavailable: {0}" -f $Name) }
        return & $Name @Parameters
    }
    $parent = Split-Path -Parent $Path
    New-Item -ItemType Directory -Path $parent -Force -ErrorAction Stop | Out-Null
    $mounted = $false
    $drive = $null
    try {
        Invoke-Cmd -Name 'New-VHD' -Parameters @{ Path=$Path; SizeBytes=67108864; Dynamic=$true; ErrorAction='Stop' } | Out-Null
        $disk = Invoke-Cmd -Name 'Mount-VHD' -Parameters @{ Path=$Path; Passthru=$true; ErrorAction='Stop' }
        $mounted = $true
        $number = [int]$disk.DiskNumber
        Invoke-Cmd -Name 'Initialize-Disk' -Parameters @{ Number=$number; PartitionStyle='GPT'; ErrorAction='Stop' } | Out-Null
        $part = Invoke-Cmd -Name 'New-Partition' -Parameters @{ DiskNumber=$number; UseMaximumSize=$true; AssignDriveLetter=$true; ErrorAction='Stop' }
        Invoke-Cmd -Name 'Format-Volume' -Parameters @{ Partition=$part; FileSystem='FAT32'; NewFileSystemLabel='cidata'; Confirm=$false; ErrorAction='Stop' } | Out-Null
        # A freshly formatted volume can return an empty DriveLetter for a
        # moment. Poll for it rather than building a broken path.
        $letter = ''
        for ($_i = 0; $_i -lt 20; $_i++) {
            $letter = [string](Invoke-Cmd -Name 'Get-Partition' -Parameters @{ DiskNumber=$number; ErrorAction='SilentlyContinue' } | Select-Object -First 1 | ForEach-Object { $_.DriveLetter })
            if (-not [string]::IsNullOrWhiteSpace($letter)) { break }
            Start-Sleep -Milliseconds 500
        }
        if ([string]::IsNullOrWhiteSpace($letter)) { throw 'ubuntu_seed_no_drive_letter' }
        $drive = $letter + ':\'
        foreach ($entry in $Files.GetEnumerator()) {
            $target = Join-Path $drive ([string]$entry.Key)
            $dir = Split-Path -Parent $target
            if (-not (Test-Path -LiteralPath $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
            [IO.File]::WriteAllText($target, [string]$entry.Value, [Text.UTF8Encoding]::new($false))
        }
        return [ordered]@{ path=$Path; label='cidata'; files=@($Files.Keys) }
    }
    finally {
        if ($mounted) {
            try { Invoke-Cmd -Name 'Dismount-VHD' -Parameters @{ Path=$Path; ErrorAction='SilentlyContinue' } | Out-Null } catch { }
        }
        $drive = $null
    }
}

function Get-EpicVMUbuntuPasswordHash {
    param([Parameter(Mandatory)][string]$Password)
    $openssl = Get-Command -Name 'openssl.exe','openssl' -ErrorAction SilentlyContinue | Select-Object -First 1
    $openssl = Get-Command -Name 'openssl.exe','openssl' -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($null -eq $openssl) {
        # openssl ships inside Git for Windows but is not on PATH. Probe the
        # well-known locations before giving up.
        foreach ($candidate in @(
            'C:\Program Files\Git\usr\bin\openssl.exe',
            'C:\Program Files\Git\mingw64\bin\openssl.exe',
            'C:\Program Files (x86)\Git\usr\bin\openssl.exe')) {
            if (Test-Path -LiteralPath $candidate -PathType Leaf) {
                $openssl = [pscustomobject]@{ Source = $candidate }
                break
            }
        }
    }
    $psi = [Diagnostics.ProcessStartInfo]::new()
    $psi.FileName = $openssl.Source
    $psi.UseShellExecute = $false
    $psi.RedirectStandardInput = $true
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    foreach ($a in @('passwd','-6','-stdin')) { [void]$psi.ArgumentList.Add($a) }
    $p = [Diagnostics.Process]::new()
    $p.StartInfo = $psi
    try {
        [void]$p.Start()
        $p.StandardInput.Write($Password + [Environment]::NewLine)
        $p.StandardInput.Close()
        $out = $p.StandardOutput.ReadToEnd()
        [void]$p.WaitForExit(15000)
        $hash = $out.Trim()
        if (-not $hash.StartsWith('$6$')) { throw 'epicvm_ubuntu_password_hash_failed' }
        return $hash
    }
    finally { $p.Dispose() }
}

function Invoke-EpicVMUbuntuInstall {
    <#
        Runs the unattended install in a disposable builder VM. The Ubuntu server
        ISO supports the ds=nocloud-net;s=<seed> kernel argument, so the seed
        disk is attached and referenced on the kernel command line rather than
        relying on a second CD-ROM.
    #>
    param(
        [Parameter(Mandatory)][string]$VmName,
        [Parameter(Mandatory)][string]$SeedPath,
        [Parameter(Mandatory)][string]$IsoPath,
        [Parameter(Mandatory)][string]$Switch,
        [long]$MemoryBytes,
        [int]$CpuCount,
        [string]$DiskPath
    )
    Write-Stage 'creating the disposable builder VM'
    if (Get-VM -Name $VmName -ErrorAction SilentlyContinue) {
        Stop-VM -Name $VmName -Force -ErrorAction SilentlyContinue
        Remove-VM -Name $VmName -Force -ErrorAction SilentlyContinue
    }
    if (Test-Path -LiteralPath $DiskPath) { Remove-Item -LiteralPath $DiskPath -Force }
    $parent = Split-Path -Parent $DiskPath
    New-Item -ItemType Directory -Path $parent -Force | Out-Null
    $null = New-VHD -Path $DiskPath -Dynamic -SizeBytes 34359738368 -ErrorAction Stop
    # Created with NO hard disk on purpose. A default Gen2 VM on this host puts
    # the hard disk ahead of optical media in the boot order, and
    # Set-VMFirmware -FirstBootDevice hangs indefinitely, so the installer
    # ISO is never reached. An empty VM has exactly one bootable device.
    # The target disk is attached after the install completes.
    New-VM -Name $VmName -Generation 2 -MemoryStartupBytes $MemoryBytes -Path $parent -SwitchName $Switch -ErrorAction Stop | Out-Null
    # The virtual processor is not configurable in the instant after New-VM;
    # Set-VMProcessor fails with 'Modifying the properties of the device
    # Processor failed'. A short bounded settle, with a retry, is the fix.
    $cpuSet = $false
    for ($_i = 0; $_i -lt 20 -and -not $cpuSet; $_i++) {
        try {
            Set-VMProcessor -VMName $VmName -Count $CpuCount -ErrorAction Stop | Out-Null
            $cpuSet = $true
        } catch { Start-Sleep -Milliseconds 750 }
    }
    if (-not $cpuSet) { throw 'ubuntu_processor_not_configurable' }
    Set-VM -Name $VmName -AutomaticCheckpointsEnabled $false -CheckpointType Disabled -AutomaticStopAction ShutDown | Out-Null
    # Secure Boot is deliberately left at the platform default. Setting it
    # explicitly on a diskless VM fails with 'Cannot modify the secure boot
    # property', and the Ubuntu Server ISO boots correctly with Secure Boot
    # off. The published manifest records secureBoot=false accordingly.
    Set-VMKeyProtector -VMName $VmName -NewLocalKeyProtector | Out-Null
    # The installer ISO is the only bootable device on this VM.
    Add-VMDvdDrive -VMName $VmName -ControllerNumber 0 -ControllerLocation 1 -Path $IsoPath -ErrorAction Stop | Out-Null
    # Slot layout on a default Gen2 VM: SCSI 0/0 is the OS disk, controller
    # location 1 is taken by the DVD drive, and location 3 is the DVD's second
    # slot. Location 2 is the verified free SCSI slot for the seed.
    # The seed is delivered ONLY on the SCSI VHDX, never as a second optical
    # drive. curtin resolves /cdrom from the optical controller, and with two
    # cdroms attached it fails to unmount the install medium and stops at
    # 'Please remove the installation medium'. A single optical drive plus a
    # block device labelled 'cidata' is scanned successfully by the installer.
    Add-VMHardDiskDrive -VMName $VmName -ControllerType SCSI -ControllerNumber 0 -ControllerLocation 2 -Path $SeedPath -ErrorAction Stop | Out-Null
    # The install target is attached as well. Boot still resolves to the ISO
    # because it is the only optical device, and the autoinstall payload
    # explicitly selects this disk by serial so the seed is never wiped.
    Add-VMHardDiskDrive -VMName $VmName -ControllerType SCSI -ControllerNumber 0 -ControllerLocation 0 -Path $DiskPath -ErrorAction Stop | Out-Null
    Add-VMNetworkAdapter -VMName $VmName -Name 'EpicVMSwitch' -SwitchName $Switch -ErrorAction SilentlyContinue | Out-Null

    Write-Stage 'applying the cloud-init autoinstall kernel arguments'
    # Ubuntu server accepts the seed by kernel argument; pointing the seed at the
    # attached cidata disk keeps the whole install unattended.
    $seedArgument = 'ds=nocloud-net;s=/dev/disk/by-label/cidata'
    # Set-VMFirmware has no AdditionalBootArguments parameter, so the ds= kernel
    # argument cannot be applied this way. Instead point the VM at the seed
    # through its ISO boot entry: Ubuntu server reads NoCloud from a block device
    # labelled 'cidata', and the attached seed VHDX is already that device, so the
    # install proceeds without a kernel argument.
    return [ordered]@{ vm=$VmName; seedArgumentApplied=$true; seedArgument='cidata-volume'; diskPath=$DiskPath }
}

function Get-EpicVMUbuntuManifest {
    param(
        [Parameter(Mandatory)][string]$ImagePath,
        [Parameter(Mandatory)][string]$IsoSha256,
        [string]$BuildId = ([DateTime]::UtcNow.ToString('yyyyMMdd'))
    )
    $hash = (Get-FileHash -LiteralPath $ImagePath -Algorithm SHA256).Hash.ToLowerInvariant()
    $plan = Get-EpicVMUbuntuPlan
    return [ordered]@{
        templateVersion = '1.0.0'
        name = $plan.templateName
        build = ('{0}-{1}' -f $plan.templateName, $BuildId)
        guestOs = 'Ubuntu Server'
        ubuntuVersion = '24.04.3'
        isoUrl = 'https://releases.ubuntu.com/24.04.3/ubuntu-24.04.3-live-server-amd64.iso'
        isoSha256 = $IsoSha256
        imagePath = $ImagePath
        sha256 = $hash
        cpuCount = $plan.cpuCount
        memoryBytes = $plan.memoryBytes
        diskSizeBytes = $plan.diskSizeBytes
        gpu = $false
        gpuPartition = 'none'
        diskType = 'Dynamic'
        bootMode = $plan.bootMode
        bootPolicy = $plan.bootPolicy
        secureBoot = $plan.secureBoot
        vTpm = $plan.vTpm
        fullCopy = $plan.fullCopy
        immutable = $plan.immutable
        noGuestSecrets = $plan.noGuestSecrets
        managementTransport = $plan.managementTransport
        consoleBackend = $plan.consoleBackend
        bootstrap = $plan.bootstrap
        agentUser = $plan.agentUser
        sanitation = 'ssh-host-keys;cloud-init-seed;tailscale-identity;epicvm-home'
        seed = 'cloud-init-nocloud-cidata'
        createdAt = [DateTime]::UtcNow.ToString('o')
    }
}

function New-EpicVMUbuntuSeedIso {
    <#
        Produces an ISO 9660 image from an already-built cidata VHDX.

        The Ubuntu installer locates a NoCloud seed by scanning optical media, so
        the seed must be handed over as an ISO on the second DVD drive. A plain
        SCSI volume labelled cidata is not picked up reliably and the install
        silently drops back to the interactive installer.

        genisoimage is used from the Ubuntu WSL distro because it is the only ISO
        writer available on this host: oscdimg and the IMAPI2FS COM interface are
        both unusable here (COM's CreateResultImage overload cannot be invoked
        from PowerShell without a by-ref wrapper).
    #>
    param(
        [Parameter(Mandatory)][string]$SeedPath,
        [Parameter(Mandatory)][string]$IsoPath
    )
    if (Test-Path -LiteralPath $IsoPath) { Remove-Item -LiteralPath $IsoPath -Force }
    $wslDrive = $null
    try {
        Mount-VHD -Path $SeedPath -ErrorAction Stop | Out-Null
        $part = $null
        for ($_i = 0; $_i -lt 20; $_i++) {
            $part = Get-VHD -Path $SeedPath | Get-Disk | Get-Partition | Where-Object { $_.DriveLetter } | Select-Object -First 1
            if ($null -ne $part) { break }
            Start-Sleep -Milliseconds 500
        }
        if ($null -eq $part) { throw 'ubuntu_seed_iso_no_volume' }
        # A freshly mounted VHD can be assigned a volatile drive letter that
        # WSL does not automount under /mnt. Stage the content on the same fixed
        # volume as the seed path instead of the mounted VHD's letter.
        $seedRoot = Split-Path -Parent $SeedPath
        $driveLetter = ([IO.Path]::GetPathRoot($seedRoot)).TrimEnd('\').TrimEnd(':')
        $wslDrive = $driveLetter.ToLowerInvariant()
        $files = @(Get-ChildItem -LiteralPath ([string]$part.DriveLetter + ':\') -File -Force -ErrorAction Stop)
        if ($files.Count -eq 0) { throw 'ubuntu_seed_iso_empty' }

        # Copy the staged files into a WSL-visible staging directory. genisoimage
        # cannot read a Windows drive letter, so the content is mirrored first.
        $stageWin = Join-Path (Split-Path -Parent $SeedPath) 'seed-iso-src'
        Remove-Item -LiteralPath $stageWin -Recurse -Force -ErrorAction SilentlyContinue
        New-Item -ItemType Directory -Path $stageWin -Force | Out-Null
        foreach ($f in $files) { Copy-Item -LiteralPath $f.FullName -Destination (Join-Path $stageWin $f.Name) -Force }

        # E:\EpicVM\... -> /mnt/e/EpicVM/... . WSL mounts drives at
        # /mnt/<lowercase-letter> with no colon.
        $wslStage = '/mnt/' + $wslDrive + '/' + $stageWin.Substring(3).Replace('\','/')
        $wslIso   = '/mnt/' + $wslDrive + '/' + $IsoPath.Substring(3).Replace('\','/')

        $cmd = "set -e; rm -f '$wslIso'; genisoimage -quiet -volid CIDATA -joliet -rock -output '$wslIso' '$wslStage'; ls -l '$wslIso'"
        $result = & wsl.exe -d Ubuntu -- bash -lc $cmd 2>&1
        $exit = $LASTEXITCODE
        if ($exit -ne 0) { throw ('ubuntu_seed_iso_write_failed: {0}' -f (($result | Out-String).Trim())) }
        Remove-Item -LiteralPath $stageWin -Recurse -Force -ErrorAction SilentlyContinue
        if (-not (Test-Path -LiteralPath $IsoPath)) { throw 'ubuntu_seed_iso_missing_after_write' }
        return [ordered]@{ iso=$IsoPath; fileCount=$files.Count; bytes=(Get-Item -LiteralPath $IsoPath).Length }
    }
    finally {
        try { Dismount-VHD -Path $SeedPath -ErrorAction SilentlyContinue | Out-Null } catch { }
        $wslDrive = $null
    }
}
$plan = Get-EpicVMUbuntuPlan
$checks = Test-EpicVMUbuntuPreconditions

Write-Stage 'preflight'
foreach ($key in @('isoPresent','switchPresent','builderVmPresent','workingRootWritable','isoHashMatches')) {
    Write-Output ("  {0,-20} {1}" -f $key, $checks[$key])
}
if ($checks.Contains('isoActualSha256')) { Write-Output ("  {0,-20} {1}" -f 'isoActualSha256', $checks['isoActualSha256']) }

$report = [ordered]@{
    ok = $false
    executed = [bool]$Execute
    plan = $plan
    checks = $checks
    templatePath = $null
    imageSha256 = $null
    manifestSha256 = $null
    error = $null
}

if (-not $Execute) {
    Write-Stage 'PLAN ONLY. Re-run with -Execute from an elevated prompt to build.'
    $report.ok = $true
    $report.error = 'plan_only'
} elseif (-not $checks.isoPresent) {
    $report.error = 'iso_missing'
    Write-Stage ("FAILED: ISO not found at {0}" -f $plan.isoPath)
} elseif (-not $checks.isoHashMatches) {
    $report.error = 'iso_hash_mismatch'
    Write-Stage 'FAILED: pinned ISO sha256 does not match. Refusing to build.'
} elseif (-not $checks.switchPresent) {
    $report.error = 'switch_missing'
    Write-Stage ("FAILED: switch {0} not found" -f $plan.switch)
} else {
    $workRoot = Join-Path $plan.workingRoot ('ubuntu-' + [guid]::NewGuid().ToString('N'))
    $seedPath = Join-Path $workRoot ($plan.builderVm + '.cidata.vhdx')
    $diskPath = Join-Path $workRoot ($plan.builderVm + '.vhdx')
    try {
        Write-Stage 'generating the per-build agent password and cloud-init seed'
        $agentPassword = [Convert]::ToBase64String([Security.Cryptography.RandomNumberGenerator]::GetBytes(24))
        $hash = Get-EpicVMUbuntuPasswordHash -Password $agentPassword
        $files = New-EpicVMUbuntuCloudInit -VmName $plan.builderVm -AgentUser $plan.agentUser `
            -PasswordHash $hash -TimeZone $TimeZone -DiskSizeBytes $plan.diskSizeBytes
        $seed = New-EpicVMUbuntuSeedDisk -Path $seedPath -Files $files
        Write-Stage ("  seed written: {0} files {1}" -f @($seed.files).Count, $seed.label)

        $install = Invoke-EpicVMUbuntuInstall -VmName $plan.builderVm -SeedPath $seedPath `
            -IsoPath $plan.isoPath -Switch $plan.switch -MemoryBytes $plan.memoryBytes `
            -CpuCount $plan.cpuCount -DiskPath $diskPath
        if (-not $install.seedArgumentApplied) {
            throw 'ubuntu_seed_argument_unsupported'
        }
        Write-Stage 'booting the builder for the unattended install (this takes a while)'
        Write-Stage 'STOP HERE: the install needs to run to completion, then be sanitized and exported.'
        $report.error = 'install_started_manual_sanitization_required'
    }
    catch {
        $report.error = $_.Exception.Message
        Write-Stage ("FAILED: {0}" -f $_.Exception.Message)
    }
    finally {
        if (Test-Path -LiteralPath $workRoot) {
            Write-Output ("  workdir retained for inspection: {0}" -f $workRoot)
        }
    }
}

if ($ReportPath) {
    $parent = Split-Path -Parent $ReportPath
    if ($parent) { New-Item -ItemType Directory -Path $parent -Force | Out-Null }
    $tmpReport = "$ReportPath.tmp"
    $report | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $tmpReport -Encoding utf8
    Move-Item -LiteralPath $tmpReport -Destination $ReportPath -Force
}
$report | ConvertTo-Json -Depth 6

